name: my_automatisation

env:
  APP_NAME: "My Application"
  APP_PACKAGE: "my_app_${{ github.sha }}"

on:
  push:
    branches: ["main"]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello step
        run: echo "Hello from github actions!"

      - name: clone repository
        uses: actions/checkout@v3

      - name: List directories
        run: ls -la

        
  bye:
    runs-on: ubuntu-latest
    needs: [hello]

    steps:
      - name: Bye step
        run: echo "Bye bye!"

  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Install python 3.11
        uses: actions/setup-python@v3
        with:
          python.version: "3.11"

      - name: clone repository
        uses: actions/checkout@v3

      - name: Name of my Script
        run: |
          echo "App name: ${{ env.APP_NAME }}"
          echo "App package: ${{ env.APP_PACKAGE }}"

      - name: run my script
        run: python3 myNumbers.py
      
